In [11]:
%env PYTHONPATH=/root

env: PYTHONPATH=/root

In [7]:

import os
import torch
from torch.utils.data import DataLoader
import pandas as pd
from typing import Union

from dataset.esa import ESADataset as ESA

esa = ESA("../data", 1, "3_months", 'train', window_size=5, horizon_size=3, stride=4)
x = esa.__getitem__(1)

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [6]:
x['labels']

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0]])

In [ ]:
c = 0
LIM = 2
for x in esa.channels.rolling(window=2):
    c += 1
    print(x)
    if c == LIM: break

            channel_1  channel_2  channel_3  channel_4  channel_5  channel_6  \
timestamp
2000-01-01    0.13791   0.126334   0.126334        0.0        0.0        0.0

            channel_7  channel_8  channel_9  channel_10  ...  channel_67  \
timestamp                                                ...
2000-01-01        0.0        0.0        0.0         0.0  ...    0.996131

            channel_68  channel_69  channel_70  channel_71  channel_72  \
timestamp
2000-01-01    0.709644    0.211964    0.788153    0.811846    0.825058

            channel_73  channel_74  channel_75  channel_76
timestamp
2000-01-01    0.936218    0.977678    0.909342    0.969021

[1 rows x 76 columns]
                     channel_1  channel_2  channel_3  channel_4  channel_5  \
timestamp
2000-01-01 00:00:00    0.13791   0.126334   0.126334        0.0        0.0
2000-01-01 00:00:30    0.13791   0.126334   0.126334        0.0        0.0

                     channel_6  channel_7  channel_8  channel_9  channel_10  \
timestamp
2000-01-01 00:00:00        0.0        0.0        0.0        0.0         0.0
2000-01-01 00:00:30        0.0        0.0        0.0        0.0         0.0

                     ...  channel_67  channel_68  channel_69  channel_70  \
timestamp            ...
2000-01-01 00:00:00  ...    0.996131    0.709644    0.211964    0.788153
2000-01-01 00:00:30  ...    0.996131    0.709644    0.211964    0.788153

                     channel_71  channel_72  channel_73  channel_74  \
timestamp
2000-01-01 00:00:00    0.811846    0.825058    0.936218    0.977678
2000-01-01 00:00:30    0.811846    0.825058    0.936218    0.981776

                     channel_75  channel_76
timestamp
2000-01-01 00:00:00    0.909342    0.969021
2000-01-01 00:00:30    0.909342    0.969021

[2 rows x 76 columns]

In [28]:
x = esa.__getitem__(pd.DatetimeIndex(["2000-01-01 00:00:30"], yearfirst=True))
x

2000-01-01 00:00:30    0.137910
2000-01-01 00:00:30    0.126334
2000-01-01 00:00:30    0.126334
2000-01-01 00:00:30    0.000000
2000-01-01 00:00:30    0.000000
                         ...
2000-01-01 00:00:30    0.825058
2000-01-01 00:00:30    0.936218
2000-01-01 00:00:30    0.981776
2000-01-01 00:00:30    0.909342
2000-01-01 00:00:30    0.969021
Length: 76, dtype: float64

In [ ]:
print(esa.n_channels)
print(len(esa))
esa.dataset.head()

76
262081

,channel_1,channel_10,channel_11,channel_12,channel_13,channel_14,channel_15,channel_16,channel_17,channel_18,...,is_anomaly_telecommand_350,is_anomaly_telecommand_351,is_anomaly_telecommand_352,is_anomaly_telecommand_353,is_anomaly_telecommand_354,is_anomaly_telecommand_36,is_anomaly_telecommand_376,is_anomaly_telecommand_38,is_anomaly_telecommand_39,is_anomaly_telecommand_40
timestamp,,,,,,,,,,,,,,,,,,,,,
2000-01-01 00:00:00,0.13791,0.0,0.0,0.317175,0.371764,0.297205,0.130113,0.766769,0.349474,0.353997,...,0,0,0,0,0,0,0,0,0,0
2000-01-01 00:00:30,0.13791,0.0,0.0,0.317175,0.371764,0.297205,0.130113,0.766769,0.349474,0.353997,...,0,0,0,0,0,0,0,0,0,0
2000-01-01 00:01:00,0.13791,0.0,0.0,0.317175,0.371764,0.297205,0.130113,0.766769,0.349474,0.353997,...,0,0,0,0,0,0,0,0,0,0
2000-01-01 00:01:30,0.13791,0.0,0.0,0.317175,0.371764,0.297205,0.130113,0.766769,0.349474,0.353997,...,0,0,0,0,0,0,0,0,0,0
2000-01-01 00:02:00,0.13791,0.0,0.0,0.317175,0.371764,0.297205,0.130113,0.766769,0.349474,0.353997,...,0,0,0,0,0,0,0,0,0,0

In [8]:
d = pd.Timestamp('2000-01-01 00:00:00')
d2 = pd.Timestamp('2000-01-01 01:00:00')
print(type(esa.dataset.loc[d]))
print(type(esa.dataset.loc[d:d2]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>